/*
*********************************************************************************************************
*                                                uC/OS-II
*                                          The Real-Time Kernel
*
*                        (c) Copyright 1992-1998, Jean J. Labrosse, Plantation, FL
*                                           All Rights Reserved
*
*                                           MASTER INCLUDE FILE
*********************************************************************************************************
*/

/*
*********************************************************************************************************
* Keil C port.
*********************************************************************************************************
*/

#ifndef __INCLUDES__
#define __INCLUDES__
#include    <stdio.h>
#include    <STC89C51RC_RD_PLUS.h>
#include    "uCosii\os_cpu.h"
#include    "uCosii\os_cfg.h"
#include    "uCosii\ucos_ii.h"

#endif
